# Generated by Django 2.2 on 2019-04-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stevens_guide_app', '0003_userprofile_votelist_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(upload_to='images/restaurants'),
        ),
    ]
